### ISSUE TITLE
Viewer-level user should not see Add to Collection option from View Work page

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1992] opened 2022-10-05 13:44 UTC
When viewing a work's show page, Viewer-level users should not see the Add to Collection button.

![Screen Shot 2022-10-05 at 9.43.24 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/1cf361ba-4b55-4e65-b31d-d1b8503116fd)

I think this has been identified in prior upgrade testing, but creating a new ticket just in case.

**Comment by bwatson78** [comment] 2022-10-05 17:06
This may be a duplicate of #1783. @eporter23 ?

**Closed** 2022-10-06 14:03 UTC
Labels: bug, duplicate, Software Engineering
