### ISSUE TITLE
Investigate saving files in Fedora/S3 via Prod

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#262] opened 2019-06-19 18:14 UTC

**Comment by mprefer** [comment] 2019-07-18 14:19
After Collin elevated me to admin status in production, I can testing from the bottom up.
1) tested that 'aws s3' commands functioned properly by copying file to bucket and listing bucket contents.
2) verified traffic via tshark packet capture.
3) uploaded a music file with some dummy metadata.
4) confirmed file existed in bucket. Could download file and play in RhythmBox.
5) noticed an existing PNG file in the bucket...I assume Collin uploaded that after fixing the admin snafu.
6) deleted object inthe UI. However, the content remained in the S3 bucket. Issue, or by design?

**Comment by eporter23** [comment] 2019-07-19 13:35
Closing this based on standup review. I also created another ticket to track the behavior noted in item 6 above.

**Closed by eporter23** 2019-07-19 13:35 UTC
Labels: DevOps, Software Engineering
